export { default as TagsInputRoot, type TagsInputRootProps, type TagsInputRootEmits } from './TagsInputRoot.vue'
export { default as TagsInputInput, type TagsInputInputProps } from './TagsInputInput.vue'
export { default as TagsInputItem, type TagsInputItemProps } from './TagsInputItem.vue'
export { default as TagsInputItemText, type TagsInputItemTextProps } from './TagsInputItemText.vue'
export { default as TagsInputItemDelete, type TagsInputItemDeleteProps } from './TagsInputItemDelete.vue'
export { default as TagsInputClear, type TagsInputClearProps } from './TagsInputClear.vue'
