export { default as TagsInputRoot } from './TagsInputRoot.vue'
export { default as TagsInputInput } from './TagsInputInput.vue'
export { default as TagsInputItem } from './TagsInputItem.vue'
export { default as TagsInputItemText } from './TagsInputItemText.vue'
export { default as TagsInputItemDelete } from './TagsInputItemDelete.vue'
export { default as TagsInputCancel } from './TagsInputCancel.vue'
