/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('radix-vue')['AccordionContent']
    AccordionDemo: typeof import('./src/components/Demo/AccordionDemo.vue')['default']
    AccordionHeader: typeof import('radix-vue')['AccordionHeader']
    AccordionItem: typeof import('radix-vue')['AccordionItem']
    AccordionRoot: typeof import('radix-vue')['AccordionRoot']
    AccordionTrigger: typeof import('radix-vue')['AccordionTrigger']
    AlertDialogDemo: typeof import('./src/components/Demo/AlertDialogDemo.vue')['default']
    AspectRatioDemo: typeof import('./src/components/Demo/AspectRatioDemo.vue')['default']
    AvatarDemo: typeof import('./src/components/Demo/AvatarDemo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CheckboxDemo: typeof import('./src/components/Demo/CheckboxDemo.vue')['default']
    CollapsibleDemo: typeof import('./src/components/Demo/CollapsibleDemo.vue')['default']
    ContextMenuDemo: typeof import('./src/components/Demo/ContextMenuDemo.vue')['default']
    DialogDemo: typeof import('./src/components/Demo/DialogDemo.vue')['default']
    DropdownMenuDemo: typeof import('./src/components/Demo/DropdownMenuDemo.vue')['default']
    HoverCardDemo: typeof import('./src/components/Demo/HoverCardDemo.vue')['default']
    LabelDemo: typeof import('./src/components/Demo/LabelDemo.vue')['default']
    MenubarDemo: typeof import('./src/components/Demo/MenubarDemo.vue')['default']
    NavigationMenuDemo: typeof import('./src/components/Demo/NavigationMenuDemo.vue')['default']
    NavigationMenuListItem: typeof import('./src/components/Demo/NavigationMenuListItem.vue')['default']
    PopoverDemo: typeof import('./src/components/Demo/PopoverDemo.vue')['default']
    ProgressDemo: typeof import('./src/components/Demo/ProgressDemo.vue')['default']
    RadioGroupDemo: typeof import('./src/components/Demo/RadioGroupDemo.vue')['default']
    ScrollAreaDemo: typeof import('./src/components/Demo/ScrollAreaDemo.vue')['default']
    SelectDemo: typeof import('./src/components/Demo/SelectDemo.vue')['default']
    SelectMultipleDemo: typeof import('./src/components/Demo/SelectMultipleDemo.vue')['default']
    SeparatorDemo: typeof import('./src/components/Demo/SeparatorDemo.vue')['default']
    SliderDemo: typeof import('./src/components/Demo/SliderDemo.vue')['default']
    SwitchDemo: typeof import('./src/components/Demo/SwitchDemo.vue')['default']
    TabsDemo: typeof import('./src/components/Demo/TabsDemo.vue')['default']
    ToggleDemo: typeof import('./src/components/Demo/ToggleDemo.vue')['default']
    ToggleGroupDemo: typeof import('./src/components/Demo/ToggleGroupDemo.vue')['default']
    ToolbarDemo: typeof import('./src/components/Demo/ToolbarDemo.vue')['default']
    TooltipDemo: typeof import('./src/components/Demo/TooltipDemo.vue')['default']
  }
}
