/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./../../docs/components/demo/Accordion/index.vue')['default']
    AlertDialog: typeof import('./../../docs/components/demo/AlertDialog/index.vue')['default']
    AspectRatio: typeof import('./../../docs/components/demo/AspectRatio/index.vue')['default']
    Avatar: typeof import('./../../docs/components/demo/Avatar/index.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Checkbox: typeof import('./../../docs/components/demo/Checkbox/index.vue')['default']
    Collapsible: typeof import('./../../docs/components/demo/Collapsible/index.vue')['default']
    Combobox: typeof import('./../../docs/components/demo/Combobox/index.vue')['default']
    ContextMenu: typeof import('./../../docs/components/demo/ContextMenu/index.vue')['default']
    Dialog: typeof import('./../../docs/components/demo/Dialog/index.vue')['default']
    DropdownMenu: typeof import('./../../docs/components/demo/DropdownMenu/index.vue')['default']
    GettingStarted: typeof import('./../../docs/components/demo/GettingStarted/index.vue')['default']
    HoverCard: typeof import('./../../docs/components/demo/HoverCard/index.vue')['default']
    Label: typeof import('./../../docs/components/demo/Label/index.vue')['default']
    Menubar: typeof import('./../../docs/components/demo/Menubar/index.vue')['default']
    NavigationMenu: typeof import('./../../docs/components/demo/NavigationMenu/index.vue')['default']
    NavigationMenuNavigationMenuListItem: typeof import('./../../docs/components/demo/NavigationMenu/NavigationMenuListItem.vue')['default']
    Pagination: typeof import('./../../docs/components/demo/Pagination/index.vue')['default']
    Popover: typeof import('./../../docs/components/demo/Popover/index.vue')['default']
    Progress: typeof import('./../../docs/components/demo/Progress/index.vue')['default']
    RadioGroup: typeof import('./../../docs/components/demo/RadioGroup/index.vue')['default']
    ScrollArea: typeof import('./../../docs/components/demo/ScrollArea/index.vue')['default']
    Select: typeof import('./../../docs/components/demo/Select/index.vue')['default']
    Separator: typeof import('./../../docs/components/demo/Separator/index.vue')['default']
    Slider: typeof import('./../../docs/components/demo/Slider/index.vue')['default']
    Switch: typeof import('./../../docs/components/demo/Switch/index.vue')['default']
    Tabs: typeof import('./../../docs/components/demo/Tabs/index.vue')['default']
    Toast: typeof import('./../../docs/components/demo/Toast/index.vue')['default']
    Toggle: typeof import('./../../docs/components/demo/Toggle/index.vue')['default']
    ToggleGroup: typeof import('./../../docs/components/demo/ToggleGroup/index.vue')['default']
    Toolbar: typeof import('./../../docs/components/demo/Toolbar/index.vue')['default']
    Tooltip: typeof import('./../../docs/components/demo/Tooltip/index.vue')['default']
  }
}
